version: "3.9"
   
services:
  django:
    build: ./backend
    command: >
        bash -c "python ./src/manage.py makemigrations
        && python ./src/manage.py migrate
        && python ./src/manage.py runserver 0.0.0.0:8000"    
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    links:
      - "django"
