version: "3.9"
   
services:
  backend:
    build: .
    command: >
        bash -c "python ./backend/src/manage.py makemigrations
        && python ./backend/src/manage.py migrate
        && python ./backend/src/manage.py runserver 0.0.0.0:8000"    
    volumes:
      - .:/code
    ports:
      - "80:8000"