
[build]
  base = "frontend/"

# api redirect.
[[redirects]]
  from = "/careerfairs/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/presentation/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/questions/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true

[[redirects]]
  from = "/user/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
# In common
[[redirects]]
  from = "/company/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/company/edit"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/company/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/student/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/student/edit"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/student/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/university/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/university/edit"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/university/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
