
[build]
  base = "frontend/"

# api redirect.
[[redirects]]
  from = "/careerfairs/*"
  to = "https://career-fairs-connect.herokuapp.com/careerfairs/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/presentation/*"
  to = "https://career-fairs-connect.herokuapp.com/presentation/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/questions/*"
  to = "https://career-fairs-connect.herokuapp.com/questions/:splat"
  status = 200  
  force = true

[[redirects]]
  from = "/user/*"
  to = "https://career-fairs-connect.herokuapp.com/user/:splat"
  status = 200  
  force = true
  
# In common
[[redirects]]
  from = "/company/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/company/edit"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/company/*"
  to = "https://career-fairs-connect.herokuapp.com/company/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/student/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/student/edit"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/student/*"
  to = "https://career-fairs-connect.herokuapp.com/student/:splat"
  status = 200  
  force = true
  
[[redirects]]
  from = "/university/"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/university/edit"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/university/*"
  to = "https://career-fairs-connect.herokuapp.com/university/:splat"
  status = 200  
  force = true
  
# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
