
[build]
  base = "frontend/"

# api redirect.
[[redirects]]
  from = "/api/*"
  to = "http://ec2-13-55-22-199.ap-southeast-2.compute.amazonaws.com/:splat"
  status = 200  
  force = true
  
# SPA router support.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
