# Generated by Django 3.2.5 on 2021-07-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('company_webpage_url', models.CharField(max_length=150)),
                ('company_logo_url', models.CharField(max_length=150)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentations',
            fields=[
                ('presentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('presentation_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('wam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stalls',
            fields=[
                ('stall_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.events')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_description', models.TextField()),
                ('application_link', models.CharField(max_length=100)),
                ('stall_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.stalls', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.universities'),
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(max_length=8)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.events')),
            ],
            options={
                'unique_together': {('event_id', 'company_id')},
            },
        ),
    ]
