# Generated by Django 3.2.5 on 2021-08-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210802_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='stall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stalls'),
        ),
    ]
