# Generated by Django 3.2.5 on 2021-08-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210801_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamessages',
            name='stall_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.stalls'),
            preserve_default=False,
        ),
    ]
