# Generated by Django 3.2.5 on 2021-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_opportunities_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='wam',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
