# Generated by Django 3.2.5 on 2021-08-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20210809_1141'),
        ('core', '0004_merge_20210809_1210'),
    ]

    operations = [
    ]
