# Generated by Django 3.2.5 on 2021-07-31 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_universities_university_site_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrations',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='event_id',
        ),
        migrations.AddField(
            model_name='stalls',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='stalls',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.careerfairs'),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
