# Generated by Django 3.2.5 on 2021-08-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20210803_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qamessages',
            old_name='upvotes',
            new_name='num_upvotes',
        ),
        migrations.RemoveField(
            model_name='qamessages',
            name='stall_id',
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_logo_64',
            field=models.CharField(max_length=2000000),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_logo_64',
            field=models.CharField(max_length=2000000),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_logo_64',
            field=models.CharField(max_length=2000000),
        ),
    ]
