# Generated by Django 3.2.5 on 2021-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210803_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalls',
            name='title',
            field=models.CharField(default='stall title', max_length=100),
            preserve_default=False,
        ),
    ]
