# Generated by Django 3.2.5 on 2021-07-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fairEvent',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('eventStart', models.DateTimeField()),
                ('eventEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stall',
            fields=[
                ('stallId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fairs.fairevent')),
            ],
        ),
    ]
