# Generated by Django 3.2.5 on 2021-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='wam',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
