# Generated by Django 3.2.5 on 2021-08-02 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='company_logo_url',
            new_name='company_logo_64',
        ),
        migrations.RenameField(
            model_name='qamessages',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_logo_url',
            new_name='student_logo_64',
        ),
        migrations.RenameField(
            model_name='universities',
            old_name='university_logo_url',
            new_name='university_logo_64',
        ),
        migrations.RemoveField(
            model_name='presentations',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='qamessages',
            name='parent_post_id',
        ),
        migrations.AddField(
            model_name='opportunities',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunities',
            name='link',
            field=models.CharField(default='www.default.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunities',
            name='location',
            field=models.CharField(default='syd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunities',
            name='role',
            field=models.CharField(default='your mum', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunities',
            name='type',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunities',
            name='wam',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentations',
            name='color',
            field=models.CharField(default="rbg('1','1','1')", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentations',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentations',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentations',
            name='title',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qamessages',
            name='question',
            field=models.TextField(default='wwhat are u?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qamessages',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stalls',
            name='stall_description',
            field=models.TextField(default='descripion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Upvotes',
        ),
    ]
