# Generated by Django 3.2.5 on 2021-08-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_logo_url',
            field=models.CharField(max_length=20000000),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_logo_url',
            field=models.CharField(max_length=200000000),
        ),
        migrations.AlterField(
            model_name='universities',
            name='university_logo_url',
            field=models.CharField(max_length=20000000),
        ),
    ]
