# Generated by Django 3.2.5 on 2021-07-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'university'), (1, 'student'), (2, 'company')], default=0),
        ),
    ]
