# Generated by Django 3.2.5 on 2021-08-07 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stalls',
            name='stall_description',
        ),
        migrations.RemoveField(
            model_name='stalls',
            name='title',
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='stall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stalls'),
        ),
    ]
