# Generated by Django 3.2.5 on 2021-07-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='stall_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.stalls'),
        ),
    ]
