# Generated by Django 3.2.5 on 2021-07-18 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qamessages_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='stall_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='core.stalls'),
        ),
        migrations.AlterField(
            model_name='students',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
