# Generated by Django 3.2.5 on 2021-07-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210729_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFairs',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.universities')),
            ],
        ),
    ]
