# Generated by Django 3.2.5 on 2021-08-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210807_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunities',
            name='link',
        ),
    ]
