# Generated by Django 3.2.5 on 2021-08-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presentations_textcolor'),
        ('core', '0002_remove_qamessages_responder_id'),
    ]

    operations = [
    ]
