# Generated by Django 3.2.5 on 2021-08-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20210808_2310'),
        ('core', '0003_merge_20210808_2347'),
    ]

    operations = [
    ]
