# Generated by Django 3.2.5 on 2021-07-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210719_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presentations',
            name='presentation_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='stall_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.stalls'),
        ),
        migrations.AlterField(
            model_name='upvotes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.qamessages'),
        ),
        migrations.AlterField(
            model_name='upvotes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Students_opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opportunities')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
            options={
                'unique_together': {('student_id', 'job_id')},
            },
        ),
    ]
