# Generated by Django 3.2.5 on 2021-08-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_presentations_stall_id'),
        ('core', '0003_qamessages_stall_id'),
    ]

    operations = [
    ]
