# Generated by Django 3.2.5 on 2021-07-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210731_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalls',
            name='approval_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
