# Generated by Django 3.2.5 on 2021-08-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20210809_1400'),
        ('core', '0005_merge_20210809_1430'),
    ]

    operations = [
    ]
