# Generated by Django 3.2.5 on 2021-08-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20210809_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='borderColor',
            field=models.CharField(default='black', max_length=255),
        ),
    ]
