# Generated by Django 3.2.5 on 2021-08-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20210809_1636'),
        ('core', '0006_presentations_bordercolor'),
    ]

    operations = [
    ]
