# Generated by Django 3.2.5 on 2021-08-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stalls_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamessages',
            name='stall_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.stalls'),
            preserve_default=False,
        ),
    ]
